### ISSUE TITLE
extension don't see mops packages

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/vscode-motoko#177] opened 2023-02-13 06:11 UTC
Project builds fine, but in vscode I see erros like this:

![image](https://user-images.githubusercontent.com/21315978/218383512-60a2f111-f9c1-4b3c-af61-0d753d604808.png)

LS output:
```
Parsed typed AST
Loading packages for directory: e:\ic\mops
Running `mops sources` in directory: e:\ic\mops
Loading packages for directory: e:\ic\mops\backend
Received: ["--package","base",".mops\\base@0.8.1\\src","--package","time-consts",".mops\\time-consts@1.0.0\\src",""]
Package: base -> /e:/ic/mops/.mops/base@0.8.1/src (file:///e%3A/ic/mops)
Package: time-consts -> /e:/ic/mops/.mops/time-consts@1.0.0/src (file:///e%3A/ic/mops)
Checking workspace
~ /e:/ic/mops/backend/storage/storage-canister.mo (file:///e%3A/ic/mops/backend)
~ /e:/ic/mops/backend/main/validate-config.mo (file:///e%3A/ic/mops/backend)
~ /e:/ic/mops/backend/main/types.mo (file:///e%3A/ic/mops/backend)
~ /e:/ic/mops/backend/main/download-log.mo (file:///e%3A/ic/mops/backend)
~ /e:/ic/mops/backend/storage/storage-manager.mo (file:///e%3A/ic/mops/backend)
~ /e:/ic/mops/test/fail.test.mo (file:///e%3A/ic/mops)
~ /e:/ic/mops/backend/main/main-canister.mo (file:///e%3A/ic/mops/backend)
```

windows 10
vscode-motoko 0.9.1

**Comment by rvanasa** [comment] 2023-02-14 03:59
This should now be fixed in 0.9.2. Let me know otherwise and I'll take another look.

**Comment by ZenVoich** [comment] 2023-02-14 06:29
Same error.

Output:
```
Loading packages for directory: e:\ic\mops
Running `mops sources` in directory: e:\ic\mops
Loading packages for directory: e:\ic\mops\backend
Running `npx --no ic-mops sources` in directory: e:\ic\mops\backend
Received: ["--package","base",".mops\\base@0.8.1\\src","--package","time-consts",".mops\\time-consts@1.0.0\\src","--package","_","backend","--package","test","..\\packages\\test\\src",""]
Package: base -> /e:/ic/mops/.mops/base@0.8.1/src (file:///e%3A/ic/mops)
Package: time-consts -> /e:/ic/mops/.mops/time-consts@1.0.0/src (file:///e%3A/ic/mops)
Package: _ -> /e:/ic/mops/backend (file:///e%3A/ic/mops)
Package: test -> /e:/ic/packages/test/src (file:///e%3A/ic/mops)
Received: [""]
Checking workspace
~ /e:/ic/mops/backend/main/download-log.mo (file:///e%3A/ic/mops/backend)
```

**Comment by rvanasa** [comment] 2023-02-14 20:11
A few debugging questions:

- It looks like the extension is reading from a `dfx.json` file in `...\mops`, and then directly from a `mops.toml` file in `...\mops\backend`. Is this correct / intended?
- Where in the project do these errors occur, e.g. in `backend`, `test`, or everywhere?
- Is it possible to create a minimal project which runs into this same issue (and/or share this project so I can reproduce this on my end)? 

As a possible short-term fix / debugging step, you could try adding the following `dfx.json` file to `e:\ic\mops\backend`:

```json
{
  "defaults": {
    "build": {
      "packtool": "mops sources"
    }
  }
}
```

This will use the specified packtool command instead of the autodetected `npx ic-mops` command, which will make it slightly easier to debug the issue.

**Comment by ZenVoich** [comment] 2023-02-15 06:22
> It looks like the extension is reading from a dfx.json file in ...\mops, and then directly from a mops.toml file in ...\mops\backend. Is this correct and intended?

yes, `backend/mops.toml` contents:
```
[package]
baseDir = "."
```
it just changes default value of `baseDir="src"` to resolve path to `backend` not to `backend/src`.
For packages publishing to mops checked that `baseDir="src"`

> Where in the project do these errors occur, e.g. in backend, test, or everywhere?

Everywhere, in each import line importing package (except `base`)

> As a short-term fix / debugging step, you could try adding the following dfx.json file to ...\mops\backend:

there is no `dfx.json` in backend dir

**Comment by ZenVoich** [comment] 2023-02-15 06:27
Just found out that removing `backend/mops.toml` solves the problem.

> it just changes default value of baseDir="src" to resolve path to backend not to backend/src

It was intended to use root dir as "local package"  to use it as `mo:_/file.mo` instead of `../../file.mo`

Probably doesn't make much sense, I'll just delete it)

**Comment by rvanasa** [comment] 2023-02-15 17:04
Okay, good to know about the `baseDir` field. I'm glad this worked as a solution!

**Closed by rvanasa** 2023-02-15 17:04 UTC

**Comment by ottodevs** [comment] 2023-09-14 20:53
This happens to me in macOS as well, trying to import any package with the extensions results in the "package not defined" error.
