### ISSUE TITLE
extension does not recognize canister alias when project is in subdirectory

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/vscode-motoko#186] opened 2023-03-08 14:45 UTC
consider the following structure
```
my-monorepo/
  |- package.json
  |- yarn.lock
  |- workspaces/
      |- canister/
          |- Cargo.toml
          |- src/
      |- proxy/
          |- package.json
          |- src/
```
when importing a canister using the `canister:canister_name` syntax, when i launch vscode from within the `my-monorepo` folder, the following error appears
<img width="887" alt="Screenshot 2023-03-08 at 15 45 13" src="https://user-images.githubusercontent.com/32162112/223743933-8d3ff28f-e25c-4537-b91a-fc5ae0973626.png">
when launching vscode from within the `canister` folder, everything works as expected.

**Comment by rvanasa** [comment] 2023-03-08 17:11
Thank you for all these bug reports! I will include this in the backlog for the next time I get a chance to improve the extension (currently juggling a lot of projects).

**Comment by ZenVoich** [comment] 2023-03-29 13:25
Probably same issue, but I get different error:
![image](https://user-images.githubusercontent.com/21315978/228551953-0e05481d-daf3-4084-9a43-9c572bf54764.png)

dfx.json:
```
{
  "version": 1,
  "canisters": {
    "staging": {
      "type": "motoko",
      "main": "src/main.mo",
      "declarations": {
        "output": "declarations/main"
      },
      "dependencies": [
        "ledger"
      ]
    },
    "ledger": {
      "type": "custom",
      "wasm": "./declarations/ledger/ledger.wasm",
      "candid": "./declarations/ledger/ledger.private.did",
      "remote": {
        "candid": "./declarations/ledger/ledger.public.did",
        "id": {
          "ic": "ryjl3-tyaaa-aaaaa-aaaba-cai"
        }
      }
    },
    "production": {
      "type": "motoko",
      "main": "src/main.mo",
      "dependencies": [
        "ledger"
      ]
    }
  },
  "defaults": {
    "build": {
      "packtool": "vessel sources",
      "args": "--trap-on-call-error"
    }
  }
}
```

dfx deploy works well

**Comment by letmejustputthishere** [comment] 2023-03-31 07:45
no that's a different issue, we have the `dfx.json` in our projects root so we should be good. if you run `npm run start`, the vscode error disappears :)

**Comment by letmejustputthishere** [comment] 2023-03-31 08:31
actually there was a bug, you have to deploy the staging canister after you change the interface to the public interface and can't use the reinstall flag.

**Comment by letmejustputthishere** [comment] 2023-03-31 08:33
@rvanasa seems like the `.dfx/local/lsp` files don't get updated when you deploy a canister using `--mode reinstall`.
steps to reproduce:
 1. deploy ledger with private did
 2. update `dfx.json` to public did
 3. deploy ledger dependent canister with `--mode reinstall`
 4. above error message is shown

**Comment by rvanasa** [comment] 2023-04-03 22:23
Thanks for the repro; this appears to be directly caused by the issue tracked in https://github.com/dfinity/sdk/issues/2996, https://github.com/dfinity/sdk/issues/2969, and [SDK-1019](https://dfinity.atlassian.net/browse/SDK-1019). Would you mind if I closed this to help consolidate the conversation?

**Comment by letmejustputthishere** [comment] 2023-04-04 05:45
sure :)

**Closed** 2023-04-04 18:18 UTC
