### ISSUE TITLE
Import of a canister throws an error: "canister alias not defined"

### ISSUE THREAD

**Issue by av1ctor** [dfinity/vscode-motoko#25] opened 2022-05-26 14:15 UTC
My project has the Ledger canister installed locally.

When importing it using 'import Ledger "canister:ledger";', the extension throws this error:

![image](https://user-images.githubusercontent.com/35101441/170504905-e81ba031-4ca8-4e77-950b-2260f9cb9236.png)

The dfx.json has both the ledger canister defined and the dependency declared: 

![image](https://user-images.githubusercontent.com/35101441/170505236-94721f05-fb46-4562-bee0-a9f17ecd5807.png)

Deploying and building are ok, dfx doesn't show any error. That's just shown on vscode and the extensions stops checking any other syntax error even if it's in a different motoko file, making it really hard to develop any complex project.

**Comment by borovan** [comment] 2022-07-19 17:04
same here

![image](https://user-images.githubusercontent.com/84897664/179808396-1915120b-4af3-4038-bfec-af15a66732ef.png)

**Comment by ggreif** [comment] 2022-07-19 22:15
@rvanasa can you have a look?

**Comment by chenyan-dfinity** [comment] 2022-07-20 22:10
There are several layers of problems here:
1) `dfx` didn't pass `--actor-alias` to `mo-ide` as specified in https://github.com/dfinity/motoko/blob/master/design/DFX-Interface.md
2) If the user is changing the code for the imported canister without running `dfx build` or deploy, VSCode still gets the old Candid interface. How do we support getting did files on the fly without a full build or deploy?

**Comment by rvanasa** [comment] 2022-07-25 21:26
Appears to be a duplicate of dfinity/sdk#472. I just submitted a PR (dfinity/sdk#2375) to start making progress towards a solution. In the short term, this should at least remove the error messages (after running `dfx build`) using the next version of DFX.

**Comment by rvanasa** [comment] 2022-09-02 16:27
This is fixed in the upcoming release. Cheers!

**Closed by rvanasa** 2022-09-02 16:27 UTC
